In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
%cd /content/drive/MyDrive/HME/Temporal-Transformer

/content/drive/MyDrive/HME/Temporal-Transformer


In [2]:
!pip install import-ipynb
import import_ipynb

In [11]:
import utils
# from utils import get_frame_num

In [12]:
utils.get_j_neighbor

AttributeError: ignored

TypeError: ignored

In [ ]:
import numpy as np
data = np.load('Posing_1.54138969_results.npy', allow_pickle=True)


In [ ]:
x = data[1]
x.size
x

In [ ]:
# import numpy as np
# bounds = np.arange(5)
# bounds[:-1]
# pairs =[]
# for i in range(3):
#     bounds = np.arange(10)
#     augment_vector = np.full(len(bounds - 1), False, dtype=bool)
#     pairs += zip(np.repeat(i, len(bounds - 1)), bounds[:-1], bounds[1:], augment_vector)

# print(pairs)
# print(augment_vector)

[(0, 0, 1, False), (0, 1, 2, False), (0, 2, 3, False), (0, 3, 4, False), (0, 4, 5, False), (0, 5, 6, False), (0, 6, 7, False), (0, 7, 8, False), (0, 8, 9, False), (1, 0, 1, False), (1, 1, 2, False), (1, 2, 3, False), (1, 3, 4, False), (1, 4, 5, False), (1, 5, 6, False), (1, 6, 7, False), (1, 7, 8, False), (1, 8, 9, False), (2, 0, 1, False), (2, 1, 2, False), (2, 2, 3, False), (2, 3, 4, False), (2, 4, 5, False), (2, 5, 6, False), (2, 6, 7, False), (2, 7, 8, False), (2, 8, 9, False)]
[False False False False False False False False False False]


In [ ]:
np.repeat(0, 9)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
xx = x[58]
xx

In [ ]:
data

In [ ]:
data[0]    # tags, filenames, and 

In [ ]:
data[1][0]    # 2d points

In [ ]:
data[2][0]    # 3d points

In [ ]:
%cd /content/drive/MyDrive/HME/Temporal-Transformer

[Errno 2] No such file or directory: '/content/drive/MyDrive/HME/Temporal-Transformer'
/content


In [ ]:
!ls

'install permenantly.ipynb'     model.ipynb
 load_conda_environment.ipynb   Posing_1.54138969_results.npy
 load_data.ipynb	        Run_VideoFormer.ipynb
 main


In [ ]:
# for an image, retrieve the shap and pose results
import numpy as np
data = np.load('Posing_1.54138969_results.npy', allow_pickle=True)
data = np.load('Posing_1.54138969_results.npy', allow_pickle=True)
pose = data[3][0] # 24*3*3, but originally it should be 24*3. Mainly it's because 3 angles could form a transformation matrix
pose.size
shape = data [4][0]

a,b,c = data[0][0]
print(c)

print(data[0][6][1])

a == data[0][0][0]

FileNotFoundError: ignored

In [ ]:
# try to concat two matrix in axis 2
import numpy as np
a = np.ones((3,4,4))
b = np.ones((3,3)) * 2
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
print(a)
print(b)
# concat
c = np.concatenate((a, b), axis=1)
c

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


ValueError: ignored

In [ ]:
## redraw the smpl result
from main.smpl import Smpl
import numpy as np
data = np.load('Posing_1.54138969_results.npy', allow_pickle=True)


vertices, joints_3d, rotations = self.smpl(pose_and_shape, **kwargs)


In [ ]:
from utils import ZZX

In [ ]:
zzx = ZZX()
zzx.generator1()

1


In [ ]:
from utils import ZJX

ImportError: ignored

In [ ]:
from utils import Dataloader_zzx

ImportError: ignored

In [ ]:
zjx = ZJX([1,1,2])
zjx.generator()

dividing data......


In [ ]:
from data_generator import Dataloader_zzx


ImportError: ignored